### ISSUE TITLE
Problema com expressões

### ISSUE THREAD

**Issue by gAldeia** [gAldeia/Genetic-algorithm-symbolic-regression#3]
Algumas expressões criadas não são calculadas pelo eval. talvez por serem muito grandes, ou por ter alguma função mal implementada, ou algum problema com x1 e x2.
por exemplo, o programa trava (parece um loop infinito) quando tenta calcular o eval da expressão sqrt((sin((((sin(cos((((e^((((x2+((x2+(((x1-x1)^5)/x1))/(x1/5)))^2)-x2)/x2))/ln(
(x2+ln((5+x2)))))^6)))*2)/sqrt(2))-x2))/7)), sendo que são usados apenas 2 pontos (não é um processo lento, e a equação é válida)

**Comment by gAldeia** [comment]
DESCOBRI:
rad_to_degrees tá entrando em loop infinito!!!!

**Comment by gAldeia** [comment]
Ideia para solução: usar % pra diminuir o número. O objetivo daqueles whiles é reduzir ângulos que excedam 360 para ficarem sempre entre 0-360, da pra usar um mod neles

**Comment by folivetti** [comment]
if (V > 360 || V < -360) V %= 360;
if (V < 0) V = 360 - V;
